//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreSurvey
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdditionalSkuBasic
    {
        // Primitive properties
    
        public int id { get; set; }
        public string sku { get; set; }
        public string skuCode { get; set; }
    
    }
}
