//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreSurvey
{
    using System;
    using System.Collections.Generic;
    
    public partial class MustHaveSku
    {
        public MustHaveSku()
        {
            this.AdditionalSkus = new HashSet<AdditionalSku>();
            this.FixedDisplaySkus = new HashSet<FixedDisplaySku>();
            this.WaveDisplaySkus = new HashSet<WaveDisplaySku>();
        }
    
        // Primitive properties
    
        public int Id { get; set; }
        public string skus { get; set; }
        public string skuCode { get; set; }
        public Nullable<int> skuCount { get; set; }
        public int questionnaire_id { get; set; }
    
        // Navigation properties
    
        public virtual ICollection<AdditionalSku> AdditionalSkus { get; set; }
        public virtual ICollection<FixedDisplaySku> FixedDisplaySkus { get; set; }
        public virtual Questionnaire Questionnaire { get; set; }
        public virtual ICollection<WaveDisplaySku> WaveDisplaySkus { get; set; }
    
    }
}
