//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreSurvey
{
    using System;
    using System.Collections.Generic;
    
    public partial class Questionnaire
    {
        public Questionnaire()
        {
            this.HotSpots = new HashSet<HotSpot>();
            this.PointOfPurchases = new HashSet<PointOfPurchase>();
        }
    
        // Primitive properties
    
        public int Id { get; set; }
        public int shopId { get; set; }
        public string name { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string cellNo { get; set; }
        public string imageUrl1 { get; set; }
        public string imageUrl2 { get; set; }
        public string longitude { get; set; }
        public string latitude { get; set; }
        public string formId { get; set; }
    
        // Navigation properties
    
        public virtual ICollection<HotSpot> HotSpots { get; set; }
        public virtual ICollection<PointOfPurchase> PointOfPurchases { get; set; }
        public virtual Shop Shop { get; set; }
    
    }
}
