//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreSurvey
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop
    {
        // Primitive properties
    
        public int Id { get; set; }
        public string SLNO { get; set; }
        public string Region { get; set; }
        public string Territory { get; set; }
        public string Town { get; set; }
        public string ShopName { get; set; }
        public string ShopAddress { get; set; }
        public string ShopType { get; set; }
        public string SLAB { get; set; }
        public string Phon { get; set; }
        public string DMS_CODE { get; set; }
    
    }
}
