//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreSurvey
{
    using System;
    using System.Data.Entity;
    
    public partial class StoreSurveyEntities : DbContext
    {
        public StoreSurveyEntities()
            : base("name=StoreSurveyEntities")
        {
        }
    
        public DbSet<Shop> Shops { get; set; }
        public DbSet<AdditionalSku> AdditionalSkus { get; set; }
        public DbSet<FixedDisplaySku> FixedDisplaySkus { get; set; }
        public DbSet<HotSpot> HotSpots { get; set; }
        public DbSet<MustHaveSku> MustHaveSkus { get; set; }
        public DbSet<PointOfPurchase> PointOfPurchases { get; set; }
        public DbSet<Questionnaire> Questionnaires { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<WaveDisplaySku> WaveDisplaySkus { get; set; }
        public DbSet<MustHaveSkusBasic> MustHaveSkusBasics { get; set; }
        public DbSet<FixedDisplayBasic> FixedDisplayBasics { get; set; }
        public DbSet<WaveDisplayBasic> WaveDisplayBasics { get; set; }
        public DbSet<POPBasic> POPBasics { get; set; }
        public DbSet<AdditionalSkuBasic> AdditionalSkuBasics { get; set; }
        public DbSet<ShopTypesBasic> ShopTypesBasics { get; set; }
        public DbSet<HotSpotBasic> HotSpotBasics { get; set; }
        public DbSet<Role> Roles { get; set; }
        public DbSet<User> Users { get; set; }
    }
}
