//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreSurvey
{
    using System;
    using System.Collections.Generic;
    
    public partial class WaveDisplayBasic
    {
        // Primitive properties
    
        public int Id { get; set; }
        public string skus { get; set; }
        public string skuCode { get; set; }
        public Nullable<int> setNum { get; set; }
    
    }
}
